#!/usr/bin/env bash

# Install Nginx and configure it to serve a basic webpage
sudo apt update
sudo apt install -y nginx

# Add custom HTTP header to Nginx's HTTP response
sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;\n\tadd_header X-Served-By $hostname;/' /etc/nginx/nginx.conf

# Test Nginx configuration file for syntax errors
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
